# config/__init__.py
"""Configuration package for Kafka MinIO Consumer.

Usage:
    import config.settings as cfg
    print(cfg.INGESTOR_SERVER_URL)
    
    from config.constants import DOCUMENT_EXTENSIONS, DEST_RAG
"""

# Settings (env vars)
from .settings import (
    # Kafka
    KAFKA_BOOTSTRAP_SERVERS,
    KAFKA_CONSUMER_GROUP,
    KAFKA_TOPIC,
    KAFKA_AUTO_OFFSET_RESET,
    KAFKA_MAX_POLL_RECORDS,
    KAFKA_MAX_POLL_INTERVAL_MS,
    KAFKA_SESSION_TIMEOUT_MS,
    KAFKA_HEARTBEAT_INTERVAL_MS,
    # Services
    INGESTOR_SERVER_URL,
    INGESTOR_TIMEOUT,
    # MinIO
    MINIO_ENDPOINT,
    MINIO_ACCESS_KEY,
    MINIO_SECRET_KEY,
    MINIO_SECURE,
    MINIO_DEFAULT_COLLECTION,
    MINIO_SOURCES,
    # Features
    ENABLE_IMAGE_PROCESSING,
    ENABLE_AUDIO_PROCESSING,
    # Collection
    EMBEDDING_DIMENSION,
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    # Logging
    LOG_LEVEL,
    LOG_FORMAT,
    # History
    HISTORY_FILE,
    # API Endpoints (configurable via env)
    API_INGESTOR_DOCUMENTS,
    API_INGESTOR_COLLECTIONS,
    API_INGESTOR_COLLECTION,
    API_INGESTOR_STATUS,
)

# Constants
from .constants import (
    # File extensions
    DOCUMENT_EXTENSIONS,
    IMAGE_EXTENSIONS,
    AUDIO_EXTENSIONS,
    SKIP_EXTENSIONS,
    # Content types
    CONTENT_TYPE_MAP,
    DEFAULT_CONTENT_TYPE,
    # Routing
    DEST_RAG,
    DEST_SKIP,
    DEST_UNKNOWN,
    # S3 Event fields
    EVENT_NAME,
    EVENT_RECORDS,
    EVENT_S3,
    EVENT_BUCKET,
    EVENT_OBJECT,
    EVENT_KEY,
    EVENT_SIZE,
    EVENT_ETAG,
    EVENT_NAME_FIELD,
    EVENT_FIRST_RECORD_INDEX,
    EVENT_PREFIX_CREATED,
    EVENT_PREFIX_REMOVED,
    EVENT_TYPE_CREATE,
    EVENT_TYPE_DELETE,
    # Record field names (dataclass attributes)
    FIELD_FILE_NAME,
    FIELD_BUCKET,
    FIELD_COLLECTION,
    FIELD_STATUS,
    FIELD_START_TIME,
    FIELD_END_TIME,
    FIELD_DURATION_SECONDS,
    FIELD_ERROR_MESSAGE,
    FIELD_TASK_ID,
    # Record serialization output keys
    RECORD_FILE_NAME,
    RECORD_BUCKET,
    RECORD_COLLECTION,
    RECORD_START_TIME,
    RECORD_END_TIME,
    RECORD_DURATION,
    RECORD_STATUS,
    RECORD_ERROR,
    RECORD_TASK_ID,
    # Status
    STATUS_PENDING,
    STATUS_PROCESSING,
    STATUS_FINISHED,
    STATUS_FAILED,
    STATUS_SKIPPED,
    STATUS_DELETED,
    STATUS_SUCCESS,
    # Config keys (MinIO sources)
    CFG_ENDPOINT,
    CFG_ACCESS,
    CFG_SECRET,
    CFG_SECURE,
    CFG_COLLECTION,
    CFG_BUCKETS,
    # API request fields (Ingestor)
    FIELD_COLLECTION_NAME,
    FIELD_BLOCKING,
    FIELD_SPLIT_OPTIONS,
    FIELD_CHUNK_SIZE,
    FIELD_CHUNK_OVERLAP,
    FIELD_GENERATE_SUMMARY,
    FIELD_EMBEDDING_DIMENSION,
    FIELD_TASK_ID,
    # API response fields
    RESP_MESSAGE,
    RESP_ERROR,
    RESP_COLLECTIONS,
    RESP_TASK_ID,
    RESP_STATE,
    RESP_RESULT,
    RESP_FAILED_DOCUMENTS,
    RESP_VALIDATION_ERRORS,
    # Timeouts
    TIMEOUT_DEFAULT,
    TIMEOUT_UPLOAD,
    TIMEOUT_TASK_CHECK,
    TIMEOUT_MAX_TASK_WAIT,
    # Kafka defaults
    KAFKA_DEFAULT_TOPIC,
    KAFKA_DEFAULT_CONSUMER_GROUP,
    KAFKA_DEFAULT_AUTO_OFFSET_RESET,
    KAFKA_DEFAULT_MAX_POLL_RECORDS,
    KAFKA_DEFAULT_MAX_POLL_INTERVAL_MS,
    KAFKA_DEFAULT_SESSION_TIMEOUT_MS,
    KAFKA_DEFAULT_HEARTBEAT_INTERVAL_MS,
    # Collection defaults
    COLLECTION_EMBEDDING_DIMENSION,
    COLLECTION_CHUNK_SIZE,
    COLLECTION_CHUNK_OVERLAP,
)
