# config/settings.py
"""Runtime settings loaded from environment variables."""

import os

from .constants import (
    # Default values
    KAFKA_DEFAULT_TOPIC,
    KAFKA_DEFAULT_CONSUMER_GROUP,
    KAFKA_DEFAULT_AUTO_OFFSET_RESET,
    KAFKA_DEFAULT_MAX_POLL_RECORDS,
    KAFKA_DEFAULT_MAX_POLL_INTERVAL_MS,
    KAFKA_DEFAULT_SESSION_TIMEOUT_MS,
    KAFKA_DEFAULT_HEARTBEAT_INTERVAL_MS,
    TIMEOUT_UPLOAD,
    COLLECTION_EMBEDDING_DIMENSION,
    COLLECTION_CHUNK_SIZE,
    COLLECTION_CHUNK_OVERLAP,
    # API Endpoint defaults
    DEFAULT_API_INGESTOR_DOCUMENTS,
    DEFAULT_API_INGESTOR_COLLECTIONS,
    DEFAULT_API_INGESTOR_COLLECTION,
    DEFAULT_API_INGESTOR_STATUS,
    # Logging defaults
    DEFAULT_LOG_LEVEL,
    DEFAULT_LOG_FORMAT,
    # History defaults
    DEFAULT_HISTORY_FILE,
    # MinIO defaults
    DEFAULT_COLLECTION_NAME,
    # Environment variable keys
    ENV_KAFKA_BOOTSTRAP_SERVERS,
    ENV_KAFKA_TOPIC,
    ENV_CONSUMER_GROUP,
    ENV_KAFKA_AUTO_OFFSET_RESET,
    ENV_KAFKA_MAX_POLL_RECORDS,
    ENV_KAFKA_MAX_POLL_INTERVAL_MS,
    ENV_KAFKA_SESSION_TIMEOUT_MS,
    ENV_KAFKA_HEARTBEAT_INTERVAL_MS,
    ENV_INGESTOR_SERVER_URL,
    ENV_INGESTOR_TIMEOUT,
    ENV_API_INGESTOR_DOCUMENTS,
    ENV_API_INGESTOR_COLLECTIONS,
    ENV_API_INGESTOR_COLLECTION,
    ENV_API_INGESTOR_STATUS,
    ENV_MINIO_ENDPOINT,
    ENV_MINIO_ACCESS_KEY,
    ENV_MINIO_SECRET_KEY,
    ENV_MINIO_SECURE,
    ENV_COLLECTION_NAME,
    ENV_MINIO_SOURCES,
    ENV_ENABLE_IMAGE_PROCESSING,
    ENV_ENABLE_AUDIO_PROCESSING,
    ENV_EMBEDDING_DIMENSION,
    ENV_CHUNK_SIZE,
    ENV_CHUNK_OVERLAP,
    ENV_LOG_LEVEL,
    ENV_LOG_FORMAT,
    ENV_HISTORY_FILE,
)


# ==================== Helper Functions ====================

def _get_bool(key: str, default: bool = False) -> bool:
    """Get boolean from environment variable."""
    return os.getenv(key, str(default)).lower() in ('true', '1', 'yes', 'on')


def _get_int(key: str, default: int) -> int:
    """Get integer from environment variable."""
    try:
        return int(os.getenv(key, str(default)))
    except ValueError:
        return default


# ==================== Kafka Settings ====================

KAFKA_BOOTSTRAP_SERVERS = os.getenv(ENV_KAFKA_BOOTSTRAP_SERVERS)  # Required
KAFKA_CONSUMER_GROUP = os.getenv(ENV_CONSUMER_GROUP, KAFKA_DEFAULT_CONSUMER_GROUP)
KAFKA_TOPIC = os.getenv(ENV_KAFKA_TOPIC, KAFKA_DEFAULT_TOPIC)
KAFKA_AUTO_OFFSET_RESET = os.getenv(ENV_KAFKA_AUTO_OFFSET_RESET, KAFKA_DEFAULT_AUTO_OFFSET_RESET)
KAFKA_MAX_POLL_RECORDS = _get_int(ENV_KAFKA_MAX_POLL_RECORDS, KAFKA_DEFAULT_MAX_POLL_RECORDS)
KAFKA_MAX_POLL_INTERVAL_MS = _get_int(ENV_KAFKA_MAX_POLL_INTERVAL_MS, KAFKA_DEFAULT_MAX_POLL_INTERVAL_MS)
KAFKA_SESSION_TIMEOUT_MS = _get_int(ENV_KAFKA_SESSION_TIMEOUT_MS, KAFKA_DEFAULT_SESSION_TIMEOUT_MS)
KAFKA_HEARTBEAT_INTERVAL_MS = _get_int(ENV_KAFKA_HEARTBEAT_INTERVAL_MS, KAFKA_DEFAULT_HEARTBEAT_INTERVAL_MS)


# ==================== Service URLs ====================

INGESTOR_SERVER_URL = os.getenv(ENV_INGESTOR_SERVER_URL)  # Required
INGESTOR_TIMEOUT = _get_int(ENV_INGESTOR_TIMEOUT, TIMEOUT_UPLOAD)

# API Endpoints - Ingestor Server
API_INGESTOR_DOCUMENTS = os.getenv(ENV_API_INGESTOR_DOCUMENTS, DEFAULT_API_INGESTOR_DOCUMENTS)
API_INGESTOR_COLLECTIONS = os.getenv(ENV_API_INGESTOR_COLLECTIONS, DEFAULT_API_INGESTOR_COLLECTIONS)
API_INGESTOR_COLLECTION = os.getenv(ENV_API_INGESTOR_COLLECTION, DEFAULT_API_INGESTOR_COLLECTION)
API_INGESTOR_STATUS = os.getenv(ENV_API_INGESTOR_STATUS, DEFAULT_API_INGESTOR_STATUS)


# ==================== MinIO Settings ====================

MINIO_ENDPOINT = os.getenv(ENV_MINIO_ENDPOINT)  # Required
MINIO_ACCESS_KEY = os.getenv(ENV_MINIO_ACCESS_KEY)  # Required
MINIO_SECRET_KEY = os.getenv(ENV_MINIO_SECRET_KEY)  # Required
MINIO_SECURE = _get_bool(ENV_MINIO_SECURE, False)
# Single collection for all buckets - matches RAG server's COLLECTION_NAME
MINIO_DEFAULT_COLLECTION = os.getenv(ENV_COLLECTION_NAME, DEFAULT_COLLECTION_NAME)
MINIO_SOURCES = os.getenv(ENV_MINIO_SOURCES)  # JSON config for multi-source


# ==================== Feature Flags ====================

ENABLE_IMAGE_PROCESSING = _get_bool(ENV_ENABLE_IMAGE_PROCESSING, False)
ENABLE_AUDIO_PROCESSING = _get_bool(ENV_ENABLE_AUDIO_PROCESSING, False)


# ==================== Collection Settings ====================

EMBEDDING_DIMENSION = _get_int(ENV_EMBEDDING_DIMENSION, COLLECTION_EMBEDDING_DIMENSION)
CHUNK_SIZE = _get_int(ENV_CHUNK_SIZE, COLLECTION_CHUNK_SIZE)
CHUNK_OVERLAP = _get_int(ENV_CHUNK_OVERLAP, COLLECTION_CHUNK_OVERLAP)


# ==================== Logging Settings ====================

LOG_LEVEL = os.getenv(ENV_LOG_LEVEL, DEFAULT_LOG_LEVEL)
LOG_FORMAT = os.getenv(ENV_LOG_FORMAT, DEFAULT_LOG_FORMAT)


# ==================== History Settings ====================

HISTORY_FILE = os.getenv(ENV_HISTORY_FILE, DEFAULT_HISTORY_FILE)

